Repository couplog/back-end, pull requests merged in 2023-05, with the labels that each got.

#2 Feat #1 set up
  build.gradle
  src/main/java/com/dateplan/dateplan/global/config/jasypt/JasyptConfig.java
  src/main/resources/application-db.yml
  src/main/resources/application-logging.yml
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: chore

#6 Feat/#5 레디스 관련 설정 추가
  build.gradle
  src/main/resources/application-db.yml
Labels: chore

#9 Feat/#8 API 공통 응답 포맷 추가
  src/main/java/com/dateplan/dateplan/global/dto/response/ApiResponse.java
Labels: feat

#11 Feat/#10 에러 코드 정의
  src/main/java/com/dateplan/dateplan/global/dto/response/ApiResponse.java
  src/main/java/com/dateplan/dateplan/global/exception/ApplicationException.java
  src/main/java/com/dateplan/dateplan/global/exception/ErrorCode.java
  src/main/java/com/dateplan/dateplan/global/exception/handler/GlobalExceptionHandler.java
  src/main/resources/application-web.yml
  src/main/resources/application.yml
Labels: feat

#14 Feat/#7 전화번호 인증 기능 구현
  build.gradle
  src/main/java/com/dateplan/dateplan/domain/member/controller/AuthController.java
  src/main/java/com/dateplan/dateplan/domain/member/dto/PhoneAuthCodeRequest.java
  src/main/java/com/dateplan/dateplan/domain/member/dto/PhoneAuthCodeServiceRequest.java
  src/main/java/com/dateplan/dateplan/domain/member/dto/PhoneRequest.java
  src/main/java/com/dateplan/dateplan/domain/member/dto/PhoneServiceRequest.java
  src/main/java/com/dateplan/dateplan/domain/member/repository/MemberRepository.java
  src/main/java/com/dateplan/dateplan/domain/member/service/AuthService.java
  src/main/java/com/dateplan/dateplan/domain/member/service/MemberReadService.java
  src/main/java/com/dateplan/dateplan/domain/sms/service/SmsService.java
  src/main/java/com/dateplan/dateplan/domain/sms/type/SmsType.java
  src/main/java/com/dateplan/dateplan/global/exception/AlReadyRegisteredPhoneException.java
  src/main/java/com/dateplan/dateplan/global/exception/ErrorCode.java
  src/main/java/com/dateplan/dateplan/global/exception/InvalidPhoneAuthCodeException.java
  src/main/java/com/dateplan/dateplan/global/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/dateplan/dateplan/global/exception/sms/SmsSendFailException.java
  src/main/java/com/dateplan/dateplan/global/util/RandomCodeGenerator.java
  src/main/resources/application-db.yml
  src/main/resources/application-sms.yml
  src/main/resources/application.yml
Labels: feat

#13 Feat/#12 login
  build.gradle
  src/main/java/com/dateplan/dateplan/domain/member/controller/AuthController.java
  src/main/java/com/dateplan/dateplan/domain/member/dto/LoginRequest.java
  src/main/java/com/dateplan/dateplan/domain/member/dto/LoginServiceRequest.java
  src/main/java/com/dateplan/dateplan/domain/member/entity/Member.java
  src/main/java/com/dateplan/dateplan/domain/member/repository/MemberRepository.java
  src/main/java/com/dateplan/dateplan/domain/member/service/AuthService.java
  src/main/java/com/dateplan/dateplan/domain/member/service/MemberReadService.java
  src/main/java/com/dateplan/dateplan/global/auth/JwtProvider.java
  src/main/java/com/dateplan/dateplan/global/auth/MemberThreadLocal.java
  src/main/java/com/dateplan/dateplan/global/config/jasypt/JasyptConfig.java
  src/main/java/com/dateplan/dateplan/global/config/web/WebConfig.java
  src/main/java/com/dateplan/dateplan/global/constant/Auth.java
  src/main/java/com/dateplan/dateplan/global/constant/Gender.java
  src/main/java/com/dateplan/dateplan/global/exception/ApplicationException.java
  src/main/java/com/dateplan/dateplan/global/exception/ErrorCode.java
  src/main/java/com/dateplan/dateplan/global/exception/auth/MemberNotFoundException.java
  src/main/java/com/dateplan/dateplan/global/exception/auth/PasswordMismatchException.java
  src/main/java/com/dateplan/dateplan/global/exception/auth/TokenExpiredException.java
  src/main/java/com/dateplan/dateplan/global/exception/auth/TokenInvalidException.java
  src/main/java/com/dateplan/dateplan/global/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/dateplan/dateplan/global/interceptor/AuthInterceptor.java
  src/main/resources/application.yml
Labels: feat

#21 Feat/#19 login test
  src/main/java/com/dateplan/dateplan/domain/member/controller/AuthController.java
  src/main/java/com/dateplan/dateplan/domain/member/dto/AuthToken.java
  src/main/java/com/dateplan/dateplan/domain/member/dto/LoginRequest.java
  src/main/java/com/dateplan/dateplan/domain/member/service/AuthService.java
  src/main/java/com/dateplan/dateplan/global/constant/Auth.java
  src/test/java/com/dateplan/dateplan/controller/member/AuthController/AuthControllerTest.java
  src/test/java/com/dateplan/dateplan/service/member/AuthServiceTest.java
  src/test/java/com/dateplan/dateplan/service/member/JwtProviderTest.java
  src/test/java/com/dateplan/dateplan/service/sms/SmsSendClientTest.java
Labels: test
